title: Python for the Life Sciences
description: A gentle introduction to Python for life scientists
google_analytics: 
show_downloads: true
github:
  zip_url: https://github.com/amberbiology/py4lifesci/zipball/master
  tar_url: https://github.com/amberbiology/py4lifesci/tarball/master
  public: true
theme: jekyll-theme-tactile

gems:
  - jekyll-mentions
